sensor_types = {
    'strain': "Strain Gauge",
    'tilt': "Tilt",
    # 'displacement': "Displacement",
    'settlement_p': "Settlement(P)",
    'settlement_f': "Settlement(F)",
    # 'vibration': "Vibration"
}

strain_columns = {
    'test_method_1': 'test_method_1',
    'test_method_2': 'test_method_2',
    'test_method_3': 'test_method_3',
    'test_method_4': 'test_method_4',
    'test_method_5': 'test_method_5',
    'test_method_6': 'test_method_6',
    'test_method_7': 'test_method_7',
    'test_method_8': 'test_method_8',
    'test_method_9': 'test_method_9',
    'test_method_10': 'test_method_10',
    'test_method_11': 'test_method_11',
    'test_method_12': 'test_method_12',
    'test_method_13': 'test_method_13',
    'test_method_14': 'test_method_14',
    'test_method_15': 'test_method_15',
    'test_method_16': 'test_method_16',
    'test_method_17': 'test_method_17',
    'test_method_18': 'test_method_18',
    'test_method_19': 'test_method_19',
    'test_method_20': 'test_method_20',
    'test_method_21': 'test_method_21',
    'test_method_22': 'test_method_22',
    'test_method_23': 'test_method_23',
    'test_method_24': 'test_method_24',
    'test_method_25': 'test_method_25',
    'test_method_26': 'test_method_26',
    'test_method_27': 'test_method_27',
    'test_method_28': 'test_method_28',
    'test_method_29': 'test_method_29',
    'test_method_30': 'test_method_30',
    'test_method_31': 'test_method_31',
    'test_method_32': 'test_method_32',
    'test_method_33': 'test_method_33',
    'test_method_34': 'test_method_34',
    'test_method_35': 'test_method_35',
    'test_method_36': 'test_method_36',
    'test_method_37': 'test_method_37',
    'test_method_38': 'test_method_38',
    'test_method_39': 'test_method_39',
    'test_method_40': 'test_method_40',
    'test_method_41': 'test_method_41',
    'test_method_42': 'test_method_42',
    'test_method_43': 'test_method_43',
    'test_method_44': 'test_method_44',
    'test_method_45': 'test_method_45',
    'test_method_46': 'test_method_46',
    'test_method_47': 'test_method_47',
    'test_method_48': 'test_method_48',
    'test_method_49': 'test_method_49',
    'test_method_50': 'test_method_50'
}

tilt_columns = {
    'test_method_1': 'test_method_1',
    'test_method_2': 'test_method_2',
    'test_method_3': 'test_method_3',
    'test_method_4': 'test_method_4',
    'test_method_5': 'test_method_5',
    'test_method_6': 'test_method_6',
    'test_method_7': 'test_method_7',
    'test_method_8': 'test_method_8',
    'test_method_9': 'test_method_9',
    'test_method_10': 'test_method_10',
    'test_method_11': 'test_method_11',
    'test_method_12': 'test_method_12',
    'test_method_13': 'test_method_13',
    'test_method_14': 'test_method_14',
    'test_method_15': 'test_method_15',
    'test_method_16': 'test_method_16',
    'test_method_17': 'test_method_17',
    'test_method_18': 'test_method_18',
    'test_method_19': 'test_method_19',
    'test_method_20': 'test_method_20',
    'test_method_21': 'test_method_21',
    'test_method_22': 'test_method_22',
    'test_method_23': 'test_method_23',
    'test_method_24': 'test_method_24',
    'test_method_25': 'test_method_25',
    'test_method_26': 'test_method_26',
    'test_method_27': 'test_method_27',
    'test_method_28': 'test_method_28',
    'test_method_29': 'test_method_29',
    'test_method_30': 'test_method_30',
    'test_method_31': 'test_method_31',
    'test_method_32': 'test_method_32',
    'test_method_33': 'test_method_33',
    'test_method_34': 'test_method_34',
    'test_method_35': 'test_method_35',
    'test_method_36': 'test_method_36',
    'test_method_37': 'test_method_37',
    'test_method_38': 'test_method_38',
    'test_method_39': 'test_method_39',
    'test_method_40': 'test_method_40',
}

# displacement_columns = {
#     'test_method_1': 'test_method_1',
#     'test_method_2': 'test_method_2',
#     'test_method_3': 'test_method_3',
#     'test_method_4': 'test_method_4',
#     'test_method_5': 'test_method_5',
#     'test_method_6': 'test_method_6',
#     'test_method_7': 'test_method_7',
#     'test_method_8': 'test_method_8',
#     'test_method_9': 'test_method_9',
#     'test_method_10': 'test_method_10',
#     'test_method_11': 'test_method_11',
#     'test_method_12': 'test_method_12',
#     'test_method_13': 'test_method_13',
#     'test_method_14': 'test_method_14',
#     'test_method_15': 'test_method_15',
#     'test_method_16': 'test_method_16',
#     'test_method_17': 'test_method_17',
#     'test_method_18': 'test_method_18',
#     'test_method_19': 'test_method_19',
#     'test_method_20': 'test_method_20',
#     'test_method_21': 'test_method_21',
#     'test_method_22': 'test_method_22',
#     'test_method_23': 'test_method_23',
#     'test_method_24': 'test_method_24',
#     'test_method_25': 'test_method_25'
# }

settlement_p_columns = {
    'test_method_1': 'test_method_1',
    'test_method_2': 'test_method_2',
    'test_method_3': 'test_method_3',
    'test_method_4': 'test_method_4',
    'test_method_5': 'test_method_5',
    'test_method_6': 'test_method_6',
    'test_method_7': 'test_method_7',
    'test_method_8': 'test_method_8',
    'test_method_9': 'test_method_9',
    'test_method_10': 'test_method_10',
    'test_method_11': 'test_method_11',
    'test_method_12': 'test_method_12',
    'test_method_13': 'test_method_13',
    'test_method_14': 'test_method_14',
    'test_method_15': 'test_method_15',
    'test_method_16': 'test_method_16',
    'test_method_17': 'test_method_17',
    'test_method_18': 'test_method_18',
    'test_method_19': 'test_method_19',
    'test_method_20': 'test_method_20',
}

settlement_f_columns = {
    'test_method_1': 'test_method_1',
    'test_method_2': 'test_method_2',
    'test_method_3': 'test_method_3',
    'test_method_4': 'test_method_4',
    'test_method_5': 'test_method_5',
    'test_method_6': 'test_method_6',
    'test_method_7': 'test_method_7',
    'test_method_8': 'test_method_8',
    'test_method_9': 'test_method_9',
    'test_method_10': 'test_method_10',
    'test_method_11': 'test_method_11',
    'test_method_12': 'test_method_12',
    'test_method_13': 'test_method_13',
    'test_method_14': 'test_method_14',
    'test_method_15': 'test_method_15',
    'test_method_16': 'test_method_16',
    'test_method_17': 'test_method_17',
    'test_method_18': 'test_method_18',
    'test_method_19': 'test_method_19',
    'test_method_20': 'test_method_20',
}


# vibration_columns = {
#     'test_method_1': 'test_method_1',
#     'test_method_2': 'test_method_2',
#     'test_method_3': 'test_method_3',
#     'test_method_4': 'test_method_4',
#     'test_method_5': 'test_method_5',
# }

test_col={}